### ISSUE TITLE
a paper publication error 

### ISSUE THREAD

**Issue by NiNicoder** [flyingdoog/awesome-graph-explainability-papers#2]
The paper: [Deconfounding to Explanation Evaluation in Graph Neural Networks](https://openreview.net/forum?id=OKhFyMVz6t7) seems does not accept by ICLR 2022, even with relatively high scores (8 8 6 8).

**Comment by wanyu-lin** [comment]
> The paper: [Deconfounding to Explanation Evaluation in Graph Neural Networks](https://openreview.net/forum?id=OKhFyMVz6t7) seems does not accept by ICLR 2022, even with relatively high scores (8 8 6 8)

I also found this error. This paper was not accepted.

**Comment by wanyu-lin** [comment]
Hi, I am the author of the CVPR 2022 paper, which was selected as an oral presentation. The current link is the version submitted to ICLR.
Here are the updated paper link and code:
source code: https://github.com/WanyuGroup/CVPR2022-OrphicX
paper URL: https://wanyu-lin.github.io/assets/publications/wanyu-cvpr2022.pdf

**Comment by flyingdoog** [comment]
Thanks for the correction.
