### ISSUE TITLE
Paper publication update

### ISSUE THREAD

**Issue by ShichangZh** [flyingdoog/awesome-graph-explainability-papers#4]
Our paper [GStarX: Explaining Graph Neural Networks with Structure-Aware Cooperative Games](https://arxiv.org/abs/2201.12380) has been accepted by NeurIPS 2022. This repo has a big influence on people interested in graph explanation. Do you mind changing our paper description from ArXiv to NeurIPS? I appreciate your help and your effort in organizing such a great repo.

**Comment by flyingdoog** [comment]
Got it.   Thanks for the update info.

**Comment by ShichangZh** [comment]
Thanks!
