### ISSUE TITLE
How can you collect the list of new papers?

### ISSUE THREAD

**Issue by alexbui91** [flyingdoog/awesome-graph-explainability-papers#5]
It seems that the list of new papers is updated automatically. Can you share with us how do you collect the list of new papers? Which APIs are you using? If it's possible, can you share the code for the crawling process?

Thank you!

**Comment by flyingdoog** [comment]
I just keep tracking and updating these papers.

Best,
Dongsheng
________________________________
From: Alex Bui ***@***.***>
Sent: Tuesday, June 13, 2023 1:52:09 AM
To: flyingdoog/awesome-graph-explainability-papers ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [flyingdoog/awesome-graph-explainability-papers] How can you collect the list of new papers? (Issue #5)


It seems that the list of new papers is updated automatically. Can you share with us how do you collect the list of new papers? Which APIs are you using? If it's possible, can you share the code for the crawling process?

Thank you!
