### ISSUE TITLE
Paper update

### ISSUE THREAD

**Issue by msadegh97** [flyingdoog/awesome-graph-explainability-papers#6]
I believe our paper is relevant to the topic of this awesome list. Our paper titled "[Probing Graph Representations](https://proceedings.mlr.press/v206/akhondzadeh23a/akhondzadeh23a.pdf)" was presented at AISTATS 2023, and it explores probing as a model-level explanation for GNNs and graph transformers. Would you kindly consider including our paper in your repository?

**Comment by flyingdoog** [comment]
Got it!
