### ISSUE TITLE
Paper update

### ISSUE THREAD

**Issue by ZhongLIFR** [flyingdoog/awesome-graph-explainability-papers#8]
Hi, could you also include our paper "Explainable Graph Neural Networks Under Fire" (https://arxiv.org/abs/2406.06417)? Our paper is one of the first studies which show that post-hoc graph explanations are easy to be attacked by adversarial perturbations. (It is currently under review for a ML conference but I would like to share it with broad readers). Thank you :)

**Comment by flyingdoog** [comment]
Done.  Thanks!
